#! /usr/bin/env python3
# -*- coding: utf-8 -*-
##########################################################################
# NSAp - Copyright (C) CEA, 2022 - 2023
# Distributed under the terms of the CeCILL-B license, as published by
# the CEA-CNRS-INRIA. Refer to the LICENSE file or to
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html
# for details.
##########################################################################

# System import
import fire
import limri.workflows as wf


fire.Fire({
    "li2mni": wf.li2mni,
    "applytrf": wf.applytrf,
    "li2mnieyes": wf.li2mnieyes
})
